version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build 
          command: npm run buid
      - aws-s3/sync:
          from: build
          to: 's3://my-s3-bucket-genki/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
