orbs:
  win: circleci/windows@1.0.0

jobs:
  build-windows:
    executor: win/vs2019
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
Note: For Windows builds, some setup and prerequisites are different. Please refer to our Hello World on Windows.

More About Using and Authoring Orbs
